backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "src/assets/uploads"
public_folder: "../../assets/uploads"
locale: tr
collections:
  - name: blog
    label: Blog Yazıları
    folder: src/content/blog
    create: true
    slug: "{{slug}}"
    fields:
      - label: Başlık
        name: title
        widget: string
      - label: Kısa Açıklama
        name: description
        widget: text
      - label: Kategori
        name: category
        widget: string
        required: false
        hint: İstediğiniz kategori adını yazabilirsiniz (ör. Gündem, Sanat, Teknoloji).
      - label: Yayın Tarihi
        name: pubDate
        widget: datetime
        time_format: false
        date_format: YYYY-MM-DD
        format: YYYY-MM-DD
      - label: Güncelleme Tarihi
        name: updatedDate
        widget: datetime
        required: false
        time_format: false
        date_format: YYYY-MM-DD
        format: YYYY-MM-DD
      - label: Kapak Görseli
        name: heroImage
        widget: image
        required: false
      - label: İçerik
        name: body
        widget: markdown